{ ref: 'refs/heads/master',
  before: '259efca6276ffcf4c4afad8f0c4dda85b187436f',
  after: '9a37c0dc0380a0b33bdcab6283f4a0806b84a891',
  created: false,
  deleted: false,
  forced: false,
  base_ref: null,
  compare: 'https://github.com/WiskeyTango/mock-web-repo/compare/259efca6276f...9a37c0dc0380',
  commits: 
   [ { id: '35d7fd0470a24cae1e61a397a8a108b63754533d',
       tree_id: '3ffcb14ccc3fed7062bad638499e44b99acdcbcf',
       distinct: false,
       message: 'adding xyz...',
       timestamp: '2017-04-11T20:16:53-07:00',
       url: 'https://github.com/WiskeyTango/mock-web-repo/commit/35d7fd0470a24cae1e61a397a8a108b63754533d',
       author: [Object],
       committer: [Object],
       added: [Object],
       removed: [],
       modified: [] },
     { id: 'df5aa2455b506904c3e6acedaf123b4038c03a54',
       tree_id: 'd747defa69563b0b875f7b4c512d8e926c2553cd',
       distinct: false,
       message: '+z.md',
       timestamp: '2017-04-11T20:19:58-07:00',
       url: 'https://github.com/WiskeyTango/mock-web-repo/commit/df5aa2455b506904c3e6acedaf123b4038c03a54',
       author: [Object],
       committer: [Object],
       added: [Object],
       removed: [],
       modified: [] },
     { id: 'ab3eb2def839f73be6dc1c7c027a74af028aaa94',
       tree_id: 'b13025d4fb6846d90d2ec187b2c7e8fef166fe59',
       distinct: false,
       message: 'ooo',
       timestamp: '2017-04-11T20:23:04-07:00',
       url: 'https://github.com/WiskeyTango/mock-web-repo/commit/ab3eb2def839f73be6dc1c7c027a74af028aaa94',
       author: [Object],
       committer: [Object],
       added: [Object],
       removed: [],
       modified: [] },
     { id: '9a37c0dc0380a0b33bdcab6283f4a0806b84a891',
       tree_id: 'b13025d4fb6846d90d2ec187b2c7e8fef166fe59',
       distinct: true,
       message: 'Merge pull request #3 from WiskeyTango/xxxyyyzzz\n\nXxxyyyzzz',
       timestamp: '2017-04-11T20:40:55-07:00',
       url: 'https://github.com/WiskeyTango/mock-web-repo/commit/9a37c0dc0380a0b33bdcab6283f4a0806b84a891',
       author: [Object],
       committer: [Object],
       added: [Object],
       removed: [],
       modified: [] } ],
  head_commit: 
   { id: '9a37c0dc0380a0b33bdcab6283f4a0806b84a891',
     tree_id: 'b13025d4fb6846d90d2ec187b2c7e8fef166fe59',
     distinct: true,
     message: 'Merge pull request #3 from WiskeyTango/xxxyyyzzz\n\nXxxyyyzzz',
     timestamp: '2017-04-11T20:40:55-07:00',
     url: 'https://github.com/WiskeyTango/mock-web-repo/commit/9a37c0dc0380a0b33bdcab6283f4a0806b84a891',
     author: 
      { name: 'Tim Marshall',
        email: 'tim@marshall.io',
        username: 'tmarshall' },
     committer: 
      { name: 'GitHub',
        email: 'noreply@github.com',
        username: 'web-flow' },
     added: [ 'ooo.md', 'xyz.md', 'z.md' ],
     removed: [],
     modified: [] },
  repository: 
   { id: 83168065,
     name: 'mock-web-repo',
     full_name: 'WiskeyTango/mock-web-repo',
     owner: 
      { name: 'WiskeyTango',
        email: '',
        login: 'WiskeyTango',
        id: 1783213,
        avatar_url: 'https://avatars2.githubusercontent.com/u/1783213?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/WiskeyTango',
        html_url: 'https://github.com/WiskeyTango',
        followers_url: 'https://api.github.com/users/WiskeyTango/followers',
        following_url: 'https://api.github.com/users/WiskeyTango/following{/other_user}',
        gists_url: 'https://api.github.com/users/WiskeyTango/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/WiskeyTango/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/WiskeyTango/subscriptions',
        organizations_url: 'https://api.github.com/users/WiskeyTango/orgs',
        repos_url: 'https://api.github.com/users/WiskeyTango/repos',
        events_url: 'https://api.github.com/users/WiskeyTango/events{/privacy}',
        received_events_url: 'https://api.github.com/users/WiskeyTango/received_events',
        type: 'Organization',
        site_admin: false },
     private: true,
     html_url: 'https://github.com/WiskeyTango/mock-web-repo',
     description: 'for testing voyant',
     fork: false,
     url: 'https://github.com/WiskeyTango/mock-web-repo',
     forks_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/forks',
     keys_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/teams',
     hooks_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/hooks',
     issue_events_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/issues/events{/number}',
     events_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/events',
     assignees_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/assignees{/user}',
     branches_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/branches{/branch}',
     tags_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/tags',
     blobs_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/languages',
     stargazers_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/stargazers',
     contributors_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/contributors',
     subscribers_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/subscribers',
     subscription_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/subscription',
     commits_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/contents/{+path}',
     compare_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/merges',
     archive_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/downloads',
     issues_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/issues{/number}',
     pulls_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/labels{/name}',
     releases_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/releases{/id}',
     deployments_url: 'https://api.github.com/repos/WiskeyTango/mock-web-repo/deployments',
     created_at: 1488062737,
     updated_at: '2017-02-25T22:54:02Z',
     pushed_at: 1491968456,
     git_url: 'git://github.com/WiskeyTango/mock-web-repo.git',
     ssh_url: 'git@github.com:WiskeyTango/mock-web-repo.git',
     clone_url: 'https://github.com/WiskeyTango/mock-web-repo.git',
     svn_url: 'https://github.com/WiskeyTango/mock-web-repo',
     homepage: null,
     size: 1,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'JavaScript',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     open_issues_count: 0,
     forks: 0,
     open_issues: 0,
     watchers: 0,
     default_branch: 'master',
     stargazers: 0,
     master_branch: 'master',
     organization: 'WiskeyTango' },
  pusher: { name: 'tmarshall', email: 'tim@marshall.io' },
  organization: 
   { login: 'WiskeyTango',
     id: 1783213,
     url: 'https://api.github.com/orgs/WiskeyTango',
     repos_url: 'https://api.github.com/orgs/WiskeyTango/repos',
     events_url: 'https://api.github.com/orgs/WiskeyTango/events',
     hooks_url: 'https://api.github.com/orgs/WiskeyTango/hooks',
     issues_url: 'https://api.github.com/orgs/WiskeyTango/issues',
     members_url: 'https://api.github.com/orgs/WiskeyTango/members{/member}',
     public_members_url: 'https://api.github.com/orgs/WiskeyTango/public_members{/member}',
     avatar_url: 'https://avatars2.githubusercontent.com/u/1783213?v=3',
     description: '' },
  sender: 
   { login: 'tmarshall',
     id: 52420,
     avatar_url: 'https://avatars3.githubusercontent.com/u/52420?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/tmarshall',
     html_url: 'https://github.com/tmarshall',
     followers_url: 'https://api.github.com/users/tmarshall/followers',
     following_url: 'https://api.github.com/users/tmarshall/following{/other_user}',
     gists_url: 'https://api.github.com/users/tmarshall/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/tmarshall/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/tmarshall/subscriptions',
     organizations_url: 'https://api.github.com/users/tmarshall/orgs',
     repos_url: 'https://api.github.com/users/tmarshall/repos',
     events_url: 'https://api.github.com/users/tmarshall/events{/privacy}',
     received_events_url: 'https://api.github.com/users/tmarshall/received_events',
     type: 'User',
     site_admin: false } }